### ISSUE TITLE
Ledger - Sign-tx screens missing status graphics

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/extension#1066]
Adding this as a UI fix and not a bug. As i realise it might not be a quick and easy task. It is also not blocking.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/80846886/156340894-af1e42bc-34fd-4be8-8150-2a8e93818015.png">

**Comment by Shadowfiend** [comment]
We now show connectedness, but for all other states we have this:

<img width="405" alt="Screenshot 2023-05-11 at 17 03 25" src="https://github.com/tahowallet/extension/assets/8245/bc7cb7c6-b4b6-4cf7-90a2-5fa71757522a">

Mostly this is because we've got multiple states to handle:
- Connected and ready to sign
- Disconnected
- Two Ledgers connected (can't sign)
- Wrong Ledger is connected (can't sign)
- Ledger is connected but can't sign (can't sign, need blind signing).
- Ledger is busy (can't sign).

Ideally I think we'd have a third icon for above, some sort of warning state. If we can get that I think we can put status icons in extremely easily.

**Comment by VladUXUI** [comment]
![image](https://github.com/tahowallet/extension/assets/80846886/55573e19-60c9-4706-a857-ec0208a40b89)

Something like this could work. But i'm iffy on the CTA. Will give the text a bit more thinking
