### ISSUE TITLE
Galxe Web3pledge credential - missing addresses

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/extension#2678]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

This issue is not related to the extension

The Galxe Web3 'pledge credential', https://galxe.com/credential/194531900883902464, should contain all addresses that signed the Web3 pledge.

### What did not work?

Every 5 minutes, we intend to add new addresses that signed the Web3 pledge from the database to the Galxe credential. 

Now and then there's addresses that are in the database, that are missing in the Galxe credential. We're currently adding these addresses to the Galxe credential manually, and are analyzing why these addresses are missing.

**Results of the analysis so far:**
- Nov 25: 132 addresses missing in the Galxe credential. These were all the addresses that signed between 
- 25-Nov-22 15:11:16
and
25-Nov-22 16:55:43

Nov 24 and Nov 26 there were no addresses missing.

### Version

v0.18.2

**Comment by Naxsun** [comment]
Nov 27 data: No addresses missing from the Galxe credential

**Comment by greg-nagy** [comment]
I have looked into Nov 25 and we did not see any errors on the function side but the function execution has increased to ~30s from the usual 2s. 

This probably signals that something was going on the galxe api side > to fix the issue probably a check and reimport logic is needed.

**Comment by greg-nagy** [comment]
The issue is that the galxe api randomly drops addresses when running the import without any error message. 

One way to fix this is to check every address on import and reimport if failed -> this is resource intensive and would probably fail because the retry would happen in the same timeframe as the original failure. 

Prerequisite: 
- Make sure you have access for the appropriate firebase projects — login to firebase console and `tly-prd` `tly-stg` and `tly-dev` should be visible
- Setup the firebase https://github.com/tallyhowallet/tallyho.org/pull/117/files
- Deploy to a new function to stage the environment

⚠️ The stages are not setup properly here and we don't have a CI either. We must be extra careful not to deploy something to prod accidentally. [For the deployment commands see the package.json](https://github.com/tallyhowallet/tallyho.org/blob/9c5c8716c5dcbd91d671a075f5e1dd0899565a8c/manifesto-dapp-backend/functions/package.json#L10-L13)

The solution that should work better is to create a scheduled function that runs every X timeframe, queries the db for all the addresses for the last N*X timeframe, and reruns the import for all of them 
  - let's figure out an optimal X timeframe - it could be anything from 1 hour to 1 day. 
    - The bigger the timeframe, the more address we need to import > and higher the chance of flooding the galxe api. 
    - The smaller the timeframe, the closer will be the retry to the original import in time > higher the chance to share the same issue 
  - let's figure out an optimal N number. There should be enough overlap between runs for a single address import to be retried multiple times.
