### ISSUE TITLE
Compatibility with https://metamask.github.io/test-dapp/

### ISSUE THREAD

**Issue by andrewkmin** [tahowallet/extension#3299]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I'm attempting to use Taho with the metamask test dapp

### What did not work?

While connecting the dapp and loading accounts work, other methods aren't supported (e.g. deploying contracts, sending ETH/tokens, etc). I find this site a useful testing ground to validate key features/functionality.

I'm curious as to what's missing on Taho that prevents full compatibility. For reference, Metamask and Coinbase Wallet are both fully compatible. 

### Version

None

**Comment by Shadowfiend** [comment]
That site seems to use the EIP-2255 request permissions flow and seems to block the rest of the page on receiving a positive or negative result from there, but treats a provider not supporting the call as a failure that cannot enable the rest of the functionality (an incorrect assumption). As used, the permissions request doesn't actually *do* anything compared to a simple `eth_requestAccounts` call—it's not actually requesting any additional permissions, and since in practice we haven't seen any issues on real dApps it seems like EIP-2255 hasn't seen much use in the real world for its stated purpose, which is “better” permissions management.

All in all, I would consider this a bug in the dApp rather than Taho, though we may poke at supporting basic use cases of `wallet_requestPermissions` that are equivalent to what we already support.

**Comment by Shadowfiend** [comment]
This appears to have been fixed on the test dApp side, closing.
