### ISSUE TITLE
Add custom asset copy tweak

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3325]
Let's change to:

✅ **Asset already added.**
If you're not seeing it, that means your balance is 0. Have a positive balance but still not seeing it? Make sure you've disabled the "Hide asset balances under $2" options from Settings and check the Wallet tab again.

<img width="375" alt="Screen Shot 2023-04-26 at 8 52 24 PM" src="https://user-images.githubusercontent.com/7005061/234739006-1ba7ddbd-e02c-449c-9381-b897056c18e7.png">

**Comment by hyphenized** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/28708889/234751207-5acbaa74-8ca1-4796-b29e-dacd9dca0b5a.png">

I feel that the previous message conveyed this information better, although the copy was still wrong for the related setting. Note that the asset might not have been added, but already exists because it's part of a token list.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/28708889/234760305-9a27fdbe-2431-4456-8a00-c71f059b6d49.png">

**Comment by jagodarybacka** [comment]
Yeah I think that message is too long, can we maybe split it into paragraphs or add a tooltip or Notion page about it? 
cc @VladUXUI

**Comment by VladUXUI** [comment]
Users are trying to add an asset that already exists, this can be for 1 of two reasons:
1 - They have 0 balance so they don't see it 
2 - They only have dust, need to toggle off "hide assets"

I feel like the previous version had a bit better context. The "title" reinforced the state of the asset and the body text provided a fix for the edgecases.

@mr-michael can you go provide a bit more context as to why you would like to change?

**Comment by Shadowfiend** [comment]
Is there a reason we wouldn't make this reactive to what we know? That is, tell them that they should see it/they can't see it because we know the balance is below $2 and they need to drop it/tell them they can't see it because balance is 0?

Additionally, it feels like we should forcibly display all assets the user has added explicitly. I'm sure that conversation already happened and I'm a little late to it but--did we explicitly decide not to do that, or did we avoid it for technical reasons?

**Comment by VladUXUI** [comment]
> @VladUXUI Are there any UX concerns over making this reactive?
> 
Nope, having them be more specific should be awesome

**Comment by kkosiorowska** [comment]
> > @VladUXUI Are there any UX concerns over making this reactive?
> 
> Nope, having them be more specific should be awesome

We can therefore try to implement this. However, I would like to clarify all doubts. If we choose to make this reactive it looks like this [PR](https://github.com/tahowallet/extension/pull/3313) doesn't make sense at this point. Because assets will not be hidden when they have 0 balance.

What is our approach to this then?
