### ISSUE TITLE
Fix issue with OETH populating on Taho Wallet

### ISSUE THREAD

**Issue by sumpg41** [tahowallet/extension#3497]
Hey @kkosiorowska and @jagodarybacka I'm not sure this was fixed, OETH is still not populating in my test wallet

![Screenshot 2023-06-22 at 9 30 39 PM](https://github.com/tahowallet/token-list/assets/80375331/386583cb-2f90-4505-b92d-9504c4aeb138)

you can see in the screenshot above there is some OETH in the wallet

![Screenshot 2023-06-22 at 9 30 21 PM](https://github.com/tahowallet/token-list/assets/80375331/7666159a-272c-4ed9-819b-2462a32145ed)

 but it does not show up here, and it will not let me add it

_Originally posted by @sumpg41 in https://github.com/tahowallet/token-list/issues/84#issuecomment-1603510872_

**Comment by kkosiorowska** [comment]
@sumpg41 I took a closer look at this and it seems to be all good. You cannot add an OETH token because it is already in the token list.  However, it is not visible because the balance is close to zero. If the balance of this token increases, it should appear in the list. Please let me know if there is anything else I can help you. 😀

![Screenshot 2023-06-23 at 10 11 52](https://github.com/tahowallet/extension/assets/23117945/94bba836-33f8-4daa-a797-482b4a630950)

**Comment by sumpg41** [comment]
> @sumpg41 I took a closer look at this and it seems to be all good. You cannot add an OETH token because it is already in the token list. However, it is not visible because the balance is close to zero. If the balance of this token increases, it should appear in the list. Please let me know if there is anything else I can help you. 😀

@kkosiorowska how high does it need to get to appear in the list? In my experience any amount of tokens in the wallet should cause it to populate on the list

**Comment by kkosiorowska** [comment]
> how high does it need to get to appear in the list? In my experience any amount of tokens in the wallet should cause it to populate on the list

@sumpg41 The estimated balance of this token is close to zero (take a look at the image above). The token will be visible when its balance has grown enough to make sense to show it in the wallet. It is aimed at hiding the dust from the sale of my assets. Otherwise, we would show a long list of tokens with a zero balance.
