### ISSUE TITLE
Disconnecting from a dapp does not remove it's stored "current network"

### ISSUE THREAD

**Issue by hyphenized** [tahowallet/extension#3599]
To reproduce:
- Connect to a dapp 
- Open background inspector
- Check indexed db / internal-ethereum-provider / currentNetwork
- Remove the dapp from connected websites
- Reload indexed db entries

#### Correct behaviour: 
- The dapp entry should have been removed
#### Current behaviour:
- The dapp entry is not removed

**Comment by Shadowfiend** [comment]
Ooh good catch!

I think permission revocation in general is a little wobbly right now. It works in practice, but the underlying data handling feels incomplete/error prone. And the fact that this is stored in the internal provider instead of the provider bridge also feels wobbly, since the current network for internal origins should *always* be the currently-selected network in the UI (i.e., we don't need to store a separate concept of it).

I wonder if the fix here is to pull all `currentNetwork` stuff into the `dAppPermissions` table somehow… After all, permissions are per-chain id.

In particular, the provider bridge's table is `dAppPermissions`, and though it's currently set to track a `PermissionRequest`, really it's a `DAppPermission` that lives in there (it's only a request before the user interacts with it). This is an old distinction that we missed out on. We could do:

```typescript
export type PermissionRequest = {
  key: string
  origin: string
  faviconUrl: string
  chainID: string
  title: string
  accountAddress: string
}

type DAppPermission = PermissionRequest & {
  state: "request" | "allow" | "deny"
  active: boolean
}
```

Where `active: true` means this is the “active” permission for a given origin, and we maintain one active permission per origin. Switching networks changes which permission is “active”.

We'd need a pretty annoying migration to get this managed properly (pull everything from the internal ethereum provider into the associated DAppPermission), but it feels most reflective both of where this should be happening and how we should be tracking it.

We could also do a table in `ProviderBridge` that is identical to the `currentNetwork` table currently in `InternalEthereumProvider`.

🤔
