### ISSUE TITLE
issue with ethers patch: TypeError: rawResult.sort is not a function

### ISSUE THREAD

**Issue by beemeeupnow** [tahowallet/extension#3605]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to https://portal.hiddenkittencity.com/unstaked

### What did not work?

Some internal issue occurred.

I found it was due to a patch: https://github.com/tahowallet/extension/blob/e6df3e07698efe54a57cd8b08ae56269f043ee6e/patches/%40ethersproject%2Bproviders%2B5.5.3.patch#L51

### Version

v0.47.0

### Relevant log output

```shell
json-rpc-batch-provider.js:44 Uncaught (in promise) TypeError: rawResult.sort is not a function
    at then.emit.action (json-rpc-batch-provider.js:44:46)
```

**Comment by Shadowfiend** [comment]
Two issues here:
- We get an `object` instead of an array as the raw result, which leads to the Ethers error—possibly because the request array only has one entry.
- The provider is returning an error, `we can't execute this request`. I'm not sure if that's expected or if the site can handle it, but the easy solution here is to wrap responses in an array if they're not already arrays. I can make this tweak and then we can see if there are additional issues with the specific site.
